blank_issues_enabled: false
contact_links:
  - name: 📚 Docs
    url: https://github.com/BetaHuhn/github-actions-starter#readme
    about: Checkout the documentation.
  - name: 🚀 Feature Request
    url: https://github.com/BetaHuhn/github-actions-starter/discussions/new?category=ideas
    about: Share ideas for new features
  - name: ❓ Ask a Question
    url: https://github.com/BetaHuhn/github-actions-starter/discussions/new?category=q-a
    about: Ask the community for help